keys:
  - &admin_defelo 61303bbad7d1bf74efa44e3be7fe2087e4380e64
  - &host_academy age1gmp55vpd9dpmmsw6wpyd85rhgy8pp32sfg842lxl4a8tvy2agufqac3yqr

creation_rules:
  - path_regex: hosts/academy/secrets\.yml$
    key_groups:
      - pgp: [ *admin_defelo ]
        age: [ *host_academy ]
