keys:
  - &admin_defelo 61303bbad7d1bf74efa44e3be7fe2087e4380e64
  - &admin_nico 0797D2389769CA1E57B72ED92BA7811687C90DE4
  - &host_prod age13r2hmarqllghyaavnu57w8rtcsf5qgnvr65smw50fkd2c4gvrgfshhwj3n
  - &host_sandkasten age173w0p0aj8s78j3295tzatxu56quwc3grsu4g2lsr7l9hxpa4hdpsgzujqx
  - &host_test age1l0u9h7wjsdge789f4fuj0ya0cz5y6c9m7nqhlhactwlzg7rt4fxquvqdzy

creation_rules:
  - path_regex: hosts/prod/secrets\.yml$
    key_groups:
      - pgp: [*admin_defelo, *admin_nico]
        age: [*host_prod]
  - path_regex: hosts/sandkasten/secrets\.yml$
    key_groups:
      - pgp: [*admin_defelo, *admin_nico]
        age: [*host_sandkasten]
  - path_regex: hosts/test/secrets\.yml$
    key_groups:
      - pgp: [*admin_defelo, *admin_nico]
        age: [*host_test]
