name: check

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  fmt:
    runs-on: ubuntu-latest
    name: fmt
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Nix
        uses: cachix/install-nix-action@v24
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: fmt
        run: nix develop .#ci --command alejandra -c .

  eval:
    runs-on: ubuntu-latest
    name: eval
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Nix
        uses: cachix/install-nix-action@v24
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: nix eval
        run: |
          nix eval --json .#deploy-sh.hosts --apply "builtins.mapAttrs (_: v: v.config.system.build.toplevel)"
